//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.25 at 09:35:44 PM MSK 
//


package by.training.task1.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Beauty.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Beauty"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="fine"/&gt;
 *     &lt;enumeration value="lovely"/&gt;
 *     &lt;enumeration value="gorgeous"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Beauty")
@XmlEnum
public enum Beauty {

    @XmlEnumValue("fine")
    FINE("fine"),
    @XmlEnumValue("lovely")
    LOVELY("lovely"),
    @XmlEnumValue("gorgeous")
    GORGEOUS("gorgeous");
    private final String value;

    Beauty(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Beauty fromValue(String v) {
        for (Beauty c: Beauty.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
