//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.25 at 04:47:16 PM MSK 
//


package by.training.task1.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Origin.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Origin"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Australia and Oceania"/&gt;
 *     &lt;enumeration value="Asia"/&gt;
 *     &lt;enumeration value="America"/&gt;
 *     &lt;enumeration value="Africa"/&gt;
 *     &lt;enumeration value="Europe"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Origin")
@XmlEnum
public enum Origin {

    @XmlEnumValue("Australia and Oceania")
    AUSTRALIA_AND_OCEANIA("Australia and Oceania"),
    @XmlEnumValue("Asia")
    ASIA("Asia"),
    @XmlEnumValue("America")
    AMERICA("America"),
    @XmlEnumValue("Africa")
    AFRICA("Africa"),
    @XmlEnumValue("Europe")
    EUROPE("Europe");
    private final String value;

    Origin(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Origin fromValue(String v) {
        for (Origin c: Origin.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
