//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.25 at 04:47:16 PM MSK 
//


package by.training.task1.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.time.LocalDate;


/**
 * <p>Java class for Precious complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Precious"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.example.org/gems}Gem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.example.org/gems}cutting"/&gt;
 *         &lt;element ref="{http://www.example.org/gems}get-date"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Precious", propOrder = {
        "cutting",
        "getDate"
})
public class Precious extends Gem {

    protected int cutting;
    @XmlElement(name = "get-date", required = true)
    @XmlSchemaType(name = "date")
    protected LocalDate getDate;

    /**
     * Gets the value of the cutting property.
     */
    public int getCutting() {
        return cutting;
    }

    /**
     * Sets the value of the cutting property.
     */
    public void setCutting(int value) {
        this.cutting = value;
    }

    /**
     * Gets the value of the getDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public LocalDate getGetDate() {
        return getDate;
    }

    /**
     * Sets the value of the getDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setGetDate(LocalDate value) {
        this.getDate = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;

        Precious precious = (Precious) o;

        if (cutting != precious.cutting) return false;
        return getDate.equals(precious.getDate);
    }

    @Override
    public int hashCode() {
        int result = super.hashCode();
        result = 31 * result + cutting;
        result = 31 * result + getDate.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "Precious{" +
                "cutting=" + cutting +
                ", getDate=" + getDate +
                '}' + super.toString();
    }
}
