//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.25 at 09:35:44 PM MSK 
//


package by.training.task1.entity;

public class SemiPrecious extends Gem {

    public SemiPrecious() {

    }

    protected SemiPrecious(SemiPreciousBuilder builder) {
        super(builder);
        this.beauty = builder.beauty;
    }

    protected Beauty beauty;

    public Beauty getBeauty() {
        return beauty;
    }

    public void setBeauty(Beauty value) {
        this.beauty = value;
    }

    public static class SemiPreciousBuilder extends GemBuilder<SemiPreciousBuilder> {

        private Beauty beauty;

        public SemiPreciousBuilder(String name) {
            super(name);
        }

        public SemiPreciousBuilder withBeauty(Beauty beauty) {
            this.beauty = beauty;
            return this;
        }

        public SemiPrecious build() {
            return new SemiPrecious(this);
        }

    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;

        SemiPrecious that = (SemiPrecious) o;

        return beauty == that.beauty;
    }

    @Override
    public int hashCode() {
        int result = super.hashCode();
        result = 31 * result + beauty.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "SemiPrecious{" +
                "beauty=" + beauty +
                '}'
                + super.toString();
    }
}
